apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-distribuering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secureLogs:
    enabled: true
  env:
    - name: DOKDISTFORDELING_URL
      value: {{ dokdistfordeling.url }}
    - name: DOKDISTFORDELING_API_SCOPE
      value: {{ dokdistfordeling.apiScope }}
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: "{{ kafka_pool }}"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ dokdistfordeling.host }}
